# Generated by Django 5.0.1 on 2024-01-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='key',
        ),
    ]
