# Generated by Django 5.0.1 on 2024-01-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_operation_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='login',
            field=models.CharField(default='anonim', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
