# Generated by Django 5.0.1 on 2024-01-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_person_login_person_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='money',
            field=models.FloatField(default=0),
        ),
    ]
