# Generated by Django 5.0.1 on 2024-01-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_operation_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance_RUB',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance_USD',
            field=models.FloatField(default=0),
        ),
    ]
