# Generated by Django 5.0.1 on 2024-01-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_remove_wallet_balance_wallet_balance_rub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='unit',
            field=models.CharField(default='RUB', max_length=3),
        ),
    ]
