# Generated by Django 5.0.1 on 2024-01-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_operation_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
